set npath=[Replace this with the FOLDER (directory) containing Necrobot.exe. Use quotes only if there are spaces. No brackets.]
set npath2=[Same format. Only fill this out if you have a second account]
set npath3=[Same format. Only fill this out if you have a third account]
set npath4=[Same format. Only fill this out if you have a fourth account]
set npath5=[Same format. Only fill this out if you have a fifth account]
set ppath=[Replace this with the FOLDER (directory) containing PogoLocationFeeder.GUI.exe. Use quotes only if there are spaces. No brackets.]
set qpath=[Replace this with the FOLDER (directory) containing QuickSpin.exe. Use quotes only if there are spaces. No brackets.]
